export const LegacyEvents = [
  {
    id: 9,
    title: "Calling All Founders!",
    date: "5 Aug 2026",
    location: "Hisar,Haryana,India",
    // attendees: 250,
    description: "Calling all Founders! Got an idea? Find out if it actually works.Record a 90-sec pitch.Get real reactions from 100+ students.Get real validation.",
    image: "/EventsPoster/2026_08_5.jpeg",
    year: "2026",
  },
  {
    id: 8,
    title: "Raw To Real",
    date: "17 Apr 2026",
    location: "Hisar,Haryana,India",
    attendees: "100+",
    description: "Video Editing & Freelancing Workshop",
    image: "/EventsPoster/2026_04_17.jpeg",
    year: "2026",
  },
  {
    id: 7,
    title: "5 Minute Stage",
    date: "11 Oct 2025",
    location: "Hisar,Haryana,India",
    attendees: "60+",
    description: "5 Minute Stage! A Special Saturday",
    image: "/EventsPoster/2025_10_11.jpeg",
    year: "2025",
  },
  {
    id: 6,
    title: "Develop 'Problem-Solving Eyes' Networking",
    date: "23 Aug 2025",
    location: "Hisar,Haryana,India",
    attendees: 40,
    description: "Develop 'Problem-Solving Eyes' Networking",
    image: "/EventsPoster/2025_08_23.jpeg",
    year: "2025",
  },
  {
    id: 5,
    title: "How Do I Start Freelancing",
    date: "28 April 2025",
    location: "Hisar,Haryana,India",
    attendees: 60,
    description: "Ready to scale your income? Join freelancers with 4+ years of experience to learn how to earn ₹50,000 from scratch.\nGet actionable, real-world strategies and insider insights to fast-track your freelance career today. ",
    image: "/EventsPoster/2025_04_28.jpeg",
    year: "2025",
  },
  {
    id: 4,
    title: "Level Up : Speak,Move,Live & Invest Like A Pro",
    date: "05 April 2025",
    location: "Hisar,Haryana,India",
    attendees: 50,
    description: "Topics To Be Covered: Communication Skills, Body Language, Four Fundamentals for life, Basics of stock market, insurance, and personal finance.",
    image: "/EventsPoster/2025_04_5.jpeg",
    year: "2025",
  },
  {
    id: 3,
    title: "First Impression to Financial Literacy",
    date: "29 March 2025",
    location: "Hisar,Haryana,India",
    attendees: 40,
    description: "Ready to transform your understanding of money and success? Join our practical session, First Impressions to Financial Literacy, to unlock key mindset shifts and real-world insights.Walk away with actionable, step-by-step strategies to kickstart your wealth-building journey today.",
    image: "/EventsPoster/2025_03_29.jpeg",
    year: "2025",
  },
  {
    id: 2,
    title: "Rich Mindset and Pyschology of Money",
    date: "22 March 2025",
    location: "Hisar,Haryana,India",
    attendees: 40,
    description: "Master the practical money management strategies and psychological habits needed to achieve true financial freedom.",
    image: "/EventsPoster/2025_03_22.jpeg",
    year: "2025",
  },
  {
    id: 1,
    title: "The Emotional Cycle Of Change",
    date: "22 Feb 2025",
    location: "Hisar,Haryana,India",
    attendees: 20,
    description: "WHY 95% PEOPLE WILL BE STUCK FOR THE REST OF THEIR LIVES ?",
    image: "/EventsPoster/2025_02_22.jpeg",
    year: "2025",
  },
];

export const upcomingEvents = [
  // {
  //   id: 1,
  //   title: "Develop 'Problem-Solving Eyes' and Networking",
  //   date: "August 2025",
  //   location: "Hisar,Haryana,India",
  //   attendees: 150,
  //   description: "📢 Develop 'Problem-Solving Eyes' and Networking",
  //   image: event5,
  //   year: "2025",
  // },
];